[tool.commitizen]
name = "cz_conventional_commits"
version = "1.2.1"
tag_format = "v$version"
version_files = ["src/git_llm_commit/__init__.py:__version__"]
update_changelog_on_bump = true
changelog_file = "CHANGELOG.md"
changelog_incremental = true
changelog_start_rev = "v1.0.2"
