name: Release

on:
  workflow_run:
    workflows: ['Tests']
    types:
      - completed
    branches: [main]

env:
  UV_PUBLISH_TOKEN: ${{ secrets.UV_PUBLISH_TOKEN }}

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run release script
        run: |
          chmod +x scripts/release.sh
          ./scripts/release.sh
